# Generated by Django 4.2.3 on 2023-07-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseñosIndustriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('clase', models.CharField(max_length=50)),
                ('subclase', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('D', 'Denominativa'), ('F', 'Figurativa'), ('M', 'Mixta')], max_length=50)),
                ('clase', models.CharField(choices=[('Clase 1', 'Clase 1'), ('Clase 2', 'Clase 2'), ('Clase 3', 'Clase 3')], max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelosIndustriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('clase', models.CharField(max_length=50)),
                ('subclase', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
